import "server-only";
import { prisma } from "@/lib/prisma";
import { AppError } from "@/lib/errors";
import { canManageProject } from "@/lib/permissions";
import { deleteAsset, uploadAsset } from "@/lib/cloudinary";
import { validateAttachment } from "@/lib/validators/attachment";
import { getBugAccessContext, type BugActor } from "@/features/bugs/service";

async function targetContext(bugId: string | null, commentId: string | null, actor: BugActor) { if ((bugId ? 1 : 0) + (commentId ? 1 : 0) !== 1) throw new AppError("VALIDATION_ERROR", "Choose one bug or comment target", 400); if (bugId) return { activityBugId: bugId, attachmentBugId: bugId, commentId: null, access: await getBugAccessContext(bugId, actor) }; const comment = await prisma.comment.findFirst({ where: { id: commentId!, deletedAt: null }, select: { id: true, bugId: true } }); if (!comment) throw new AppError("RESOURCE_NOT_FOUND", "Comment not found", 404); return { activityBugId: comment.bugId, attachmentBugId: null, commentId: comment.id, access: await getBugAccessContext(comment.bugId, actor) }; }
export async function listBugAttachments(bugId: string, actor: BugActor) { await getBugAccessContext(bugId, actor); return prisma.attachment.findMany({ where: { bugId }, select: { id: true, originalFileName: true, fileUrl: true, mimeType: true, fileSize: true, type: true, uploadedById: true, createdAt: true, uploadedBy: { select: { fullName: true } } }, orderBy: { createdAt: "desc" } }); }
export async function createAttachment(file: File, bugId: string | null, commentId: string | null, actor: BugActor) { const target = await targetContext(bugId, commentId, actor); const config = validateAttachment(file); const uploaded = await uploadAsset(Buffer.from(await file.arrayBuffer()), file.name, config.resource); try { return await prisma.$transaction(async (tx) => { const attachment = await tx.attachment.create({ data: { originalFileName: file.name.slice(0, 255), publicId: uploaded.publicId, fileUrl: uploaded.secureUrl, mimeType: file.type || "application/octet-stream", fileSize: file.size, type: config.type, uploadedById: actor.id, bugId: target.attachmentBugId, commentId: target.commentId } }); await tx.activityLog.create({ data: { projectId: target.access.bug.projectId, bugId: target.activityBugId, actorId: actor.id, actionType: "ATTACHMENT_ADDED", description: `Attached ${file.name.slice(0, 120)}`, metadata: { attachmentId: attachment.id, commentId: target.commentId } } }); return attachment; }); } catch (error) { await deleteAsset(uploaded.publicId, config.resource).catch(() => undefined); throw error; } }
export async function removeAttachment(id: string, actor: BugActor) { const attachment = await prisma.attachment.findUnique({ where: { id }, select: { id: true, publicId: true, type: true, uploadedById: true, originalFileName: true, bugId: true, comment: { select: { bugId: true } } } }); if (!attachment) throw new AppError("RESOURCE_NOT_FOUND", "Attachment not found", 404); const bugId = attachment.bugId ?? attachment.comment?.bugId; if (!bugId) throw new AppError("RESOURCE_NOT_FOUND", "Attachment target not found", 404); const access = await getBugAccessContext(bugId, actor); if (attachment.uploadedById !== actor.id && !canManageProject(actor.systemRole, access.role)) throw new AppError("FORBIDDEN", "You cannot delete this attachment", 403); const resource = attachment.type === "IMAGE" ? "image" : attachment.type === "VIDEO" ? "video" : "raw"; await deleteAsset(attachment.publicId, resource); await prisma.$transaction(async (tx) => { await tx.attachment.delete({ where: { id } }); await tx.activityLog.create({ data: { projectId: access.bug.projectId, bugId, actorId: actor.id, actionType: "ATTACHMENT_DELETED", description: `Deleted attachment ${attachment.originalFileName}`, metadata: { attachmentId: id } } }); }); }
