import Link from "next/link";
import { CalendarDays, ChevronLeft, Settings, Users } from "lucide-react";
import { requirePageUser } from "@/lib/auth";
import { getProject } from "@/features/projects/service";
import { ProjectStatusBadge } from "@/components/projects/project-status-badge";

export default async function ProjectPage({ params }: { params: Promise<{ projectId: string }> }) {
  const actor = await requirePageUser(); const { projectId } = await params; const project = await getProject(projectId, actor);
  const date = (value: Date | null) => value ? new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(value) : "Not set";
  return <><Link href="/projects" className="inline-flex items-center gap-1 text-sm text-slate-500 hover:text-slate-900"><ChevronLeft className="size-4" />Projects</Link><div className="mt-5 flex flex-wrap items-start justify-between gap-5"><div><div className="flex items-center gap-3"><span className="rounded-md bg-slate-200 px-2 py-1 font-mono text-xs font-semibold">{project.code}</span><ProjectStatusBadge status={project.status} /></div><h1 className="mt-4 text-3xl font-semibold tracking-tight">{project.name}</h1><p className="mt-3 max-w-2xl leading-7 text-slate-600">{project.description || "No project description."}</p></div>{project.canManage ? <Link href={`/projects/${project.id}/settings`} className="flex h-10 items-center gap-2 rounded-lg border bg-white px-4 text-sm font-medium"><Settings className="size-4" />Settings</Link> : null}</div>
    <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Members",project.members.length,Users],["Bugs",project._count.bugs,Settings],["Start date",date(project.startDate),CalendarDays],["Expected end",date(project.expectedEndDate),CalendarDays]].map(([label,value,Icon]) => { const ItemIcon = Icon as typeof Users; return <article key={String(label)} className="rounded-xl border bg-white p-5"><ItemIcon className="size-5 text-blue-600" /><p className="mt-4 text-xs text-slate-500">{String(label)}</p><p className="mt-1 font-semibold">{String(value)}</p></article>; })}</div>
    <section className="mt-8 rounded-xl border bg-white"><div className="border-b p-5"><h2 className="font-semibold">Project members</h2><p className="mt-1 text-sm text-slate-500">People with access to this project.</p></div><div className="divide-y">{project.members.map((member) => <div key={member.id} className="flex items-center gap-3 p-4"><span className="grid size-9 place-items-center rounded-full bg-blue-50 text-sm font-semibold text-blue-700">{member.user.fullName.slice(0,1)}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{member.user.fullName}</p><p className="truncate text-xs text-slate-500">@{member.user.username}</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs">{member.role}</span></div>)}</div></section></>;
}
