import Link from "next/link";
import { CalendarDays, ChevronLeft, UserRound } from "lucide-react";
import { requirePageUser } from "@/lib/auth";
import { getBug, listProjectDevelopers } from "@/features/bugs/service";
import { AssignBugForm } from "@/components/bugs/assign-bug-form";
import { BugForm } from "@/components/bugs/bug-form";
import { PriorityLabel, SeverityLabel, StatusBadge } from "@/components/bugs/bug-badges";
import { selfAssignBugAction, updatePriorityAction, updateSeverityAction } from "@/features/bugs/actions";

export default async function BugDetailPage({ params }: { params: Promise<{ bugId: string }> }) {
  const actor = await requirePageUser(); const { bugId } = await params; const bug = await getBug(bugId, actor);
  const developers = bug.canManage ? (await listProjectDevelopers(bug.project.id, actor)).map(({ user }) => user) : [];
  const sections = [["Description",bug.description],["Steps to reproduce",bug.reproductionSteps],["Expected result",bug.expectedResult],["Actual result",bug.actualResult]];
  return <><Link href="/bugs" className="inline-flex items-center gap-1 text-sm text-slate-500"><ChevronLeft className="size-4" />Bugs</Link><div className="mt-5 grid gap-8 lg:grid-cols-[minmax(0,1fr)_280px]"><div><div className="flex flex-wrap items-center gap-3"><span className="font-mono text-sm font-semibold text-blue-600">{bug.bugCode}</span><StatusBadge value={bug.status} /></div><h1 className="mt-4 text-3xl font-semibold tracking-tight">{bug.title}</h1><p className="mt-2 text-sm text-slate-500">{bug.project.name} · Reported by {bug.reporter.fullName} · {bug.createdAt.toLocaleDateString()}</p><div className="mt-8 space-y-7">{sections.map(([title,content]) => <section key={title}><h2 className="text-sm font-semibold uppercase tracking-wide text-slate-500">{title}</h2><p className="mt-2 whitespace-pre-wrap leading-7 text-slate-800">{content || "Not provided."}</p></section>)}</div>{bug.canEdit ? <section className="mt-12"><h2 className="mb-4 text-xl font-semibold">Edit bug</h2><BugForm bug={bug} /></section> : null}</div>
    <aside className="space-y-4"><section className="rounded-xl border bg-white p-5"><h2 className="text-sm font-semibold">Assignment</h2><div className="mt-4 flex items-center gap-2 text-sm"><UserRound className="size-4 text-slate-400" />{bug.assignee?.fullName ?? "Unassigned"}</div>{bug.canManage ? <div className="mt-4"><AssignBugForm bugId={bug.id} currentId={bug.assignee?.id ?? null} developers={developers} /></div> : bug.canSelfAssign ? <form action={selfAssignBugAction.bind(null, bug.id)} className="mt-4"><button className="h-10 w-full rounded-lg bg-blue-600 text-sm font-medium text-white">Assign to me</button></form> : null}</section>
      <section className="rounded-xl border bg-white p-5"><h2 className="text-sm font-semibold">Classification</h2><div className="mt-4 flex items-center justify-between"><span className="text-sm text-slate-500">Priority</span><PriorityLabel value={bug.priority} /></div><div className="mt-3 flex items-center justify-between"><span className="text-sm text-slate-500">Severity</span><SeverityLabel value={bug.severity} /></div>{bug.canManage ? <div className="mt-5 space-y-2 border-t pt-4"><form action={updatePriorityAction.bind(null, bug.id)} className="flex gap-2"><select name="priority" defaultValue={bug.priority} className="h-9 min-w-0 flex-1 rounded-lg border bg-white px-2 text-xs">{["LOW","MEDIUM","HIGH","URGENT"].map((value) => <option key={value}>{value}</option>)}</select><button className="rounded-lg border px-2 text-xs">Save</button></form><form action={updateSeverityAction.bind(null, bug.id)} className="flex gap-2"><select name="severity" defaultValue={bug.severity} className="h-9 min-w-0 flex-1 rounded-lg border bg-white px-2 text-xs">{["MINOR","MAJOR","CRITICAL","BLOCKER"].map((value) => <option key={value}>{value}</option>)}</select><button className="rounded-lg border px-2 text-xs">Save</button></form></div> : null}</section>
      <section className="rounded-xl border bg-white p-5"><h2 className="text-sm font-semibold">Environment</h2><dl className="mt-4 space-y-3 text-sm">{[["Environment",bug.environment],["Browser",bug.browser],["OS",bug.operatingSystem],["Version",bug.applicationVersion]].map(([key,value]) => <div key={key} className="flex justify-between gap-3"><dt className="text-slate-500">{key}</dt><dd className="text-right">{value || "—"}</dd></div>)}</dl>{bug.dueDate ? <div className="mt-4 flex items-center gap-2 border-t pt-4 text-sm"><CalendarDays className="size-4 text-slate-400" />Due {bug.dueDate.toLocaleDateString()}</div> : null}</section></aside></div></>;
}
