"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
type Filter = "all" | "unread" | "mention" | "deadline" | "chat" | "project" | "bug" | "urgent";
type Item = { id: string; title: string; message: string; isRead: boolean; createdAt: string; bug: { id: string; bugCode: string } | null; project: { id: string; code: string } | null; conversation: { id: string } | null; actor: { fullName: string } | null };
type Response = { success: true; data: { items: Item[]; unreadCount: number; pagination: { page: number; totalPages: number } } };
const filters: { value: Filter; label: string }[] = [{ value: "all", label: "Tất cả" }, { value: "unread", label: "Chưa đọc" }, { value: "mention", label: "Nhắc đến" }, { value: "deadline", label: "Deadline" }, { value: "chat", label: "Chat" }, { value: "project", label: "Dự án" }, { value: "bug", label: "Bug" }, { value: "urgent", label: "Khẩn cấp/Hệ thống" }];
async function fetchNotifications(page: number, filter: Filter) { const response = await fetch(`/api/notifications?page=${page}&filter=${filter}`); if (!response.ok) throw new Error(); return await response.json() as Response; }
function target(item: Item) { if (item.conversation) return `/chat?conversation=${item.conversation.id}`; if (item.bug) return `/bugs/${item.bug.id}`; if (item.project) return `/projects/${item.project.id}`; return null; }
// eslint-disable-next-line react-hooks/set-state-in-effect
export function NotificationList() { const [page, setPage] = useState(1); const [filter, setFilter] = useState<Filter>("all"); const client = useQueryClient(); useEffect(() => setPage(1), [filter]); const query = useQuery({ queryKey: ["notifications", page, filter], queryFn: () => fetchNotifications(page, filter), refetchInterval: 30_000, refetchIntervalInBackground: false, staleTime: 10_000 }); const refresh = () => client.invalidateQueries({ queryKey: ["notifications"] }); const patch = async (url: string) => { const response = await fetch(url, { method: "PATCH" }); if (!response.ok) throw new Error(); }; const read = useMutation({ mutationFn: (id: string) => patch(`/api/notifications/${id}/read`), onSuccess: refresh }); const all = useMutation({ mutationFn: () => patch("/api/notifications/read-all"), onSuccess: refresh }); const data = query.data?.data;
 return <div><div className="mb-4 flex flex-wrap gap-2" role="tablist">{filters.map((item) => <button key={item.value} role="tab" aria-selected={filter === item.value} onClick={() => setFilter(item.value)} className={`rounded-full border px-3 py-1.5 text-xs ${filter === item.value ? "border-blue-600 bg-blue-600 text-white" : "bg-white text-slate-600"}`}>{item.label}</button>)}</div><div className="mb-4 flex items-center justify-between"><span className="text-sm text-slate-500">{data?.unreadCount ?? 0} chưa đọc</span><button onClick={() => all.mutate()} disabled={!data?.unreadCount || all.isPending} className="rounded-lg border bg-white px-3 py-2 text-sm disabled:opacity-40">Đánh dấu tất cả đã đọc</button></div>{query.isLoading ? <div className="h-40 animate-pulse rounded-xl bg-slate-100" /> : query.isError ? <div className="rounded-xl bg-red-50 p-4 text-sm text-red-700">Không thể tải thông báo. <button onClick={() => query.refetch()} className="underline">Thử lại</button></div> : <div className="divide-y overflow-hidden rounded-xl border bg-white">{data?.items.length ? data.items.map((item) => { const href = target(item); return <div key={item.id} className={`p-4 ${item.isRead ? "" : "bg-blue-50/50"}`}><div className="flex gap-3"><span className={`mt-2 size-2 shrink-0 rounded-full ${item.isRead ? "bg-slate-200" : "bg-blue-600"}`} /><div className="min-w-0 flex-1"><p className="text-sm font-medium">{item.title}</p><p className="mt-1 text-sm text-slate-600">{item.message}</p><p className="mt-2 text-xs text-slate-400">{item.actor?.fullName ?? "Hệ thống"} · {new Date(item.createdAt).toLocaleString("vi-VN")}</p><div className="mt-3 flex gap-3">{href ? <Link href={href} onClick={() => !item.isRead && read.mutate(item.id)} className="text-xs font-medium text-blue-600">Mở chi tiết</Link> : null}{!item.isRead ? <button onClick={() => read.mutate(item.id)} className="text-xs text-slate-500">Đánh dấu đã đọc</button> : null}</div></div></div></div>; }) : <div className="p-8 text-center"><p className="text-sm font-medium">Không có thông báo phù hợp</p><p className="mt-1 text-xs text-slate-500">Hãy chọn bộ lọc khác hoặc quay lại sau.</p></div>}</div>}{data && data.pagination.totalPages > 1 ? <nav className="mt-4 flex items-center justify-between"><button disabled={page === 1} onClick={() => setPage((v) => v - 1)} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-40">Trước</button><span className="text-sm text-slate-500">Trang {page}/{data.pagination.totalPages}</span><button disabled={page === data.pagination.totalPages} onClick={() => setPage((v) => v + 1)} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-40">Sau</button></nav> : null}</div>; }
