"use client";

import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type Point = { name: string; value: number };
const colors = ["#2563eb", "#7c3aed", "#0891b2", "#059669", "#d97706", "#dc2626", "#475569", "#db2777", "#65a30d"];
function ChartBox({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">{title}</h2><div className="mt-5 h-72">{children}</div></section>; }
const tooltipStyle = { borderRadius: 8, borderColor: "#e2e8f0", fontSize: 12 };

export function ProjectCharts({ byStatus, byPriority, bySeverity, byAssignee, daily }: { byStatus: Point[]; byPriority: Point[]; bySeverity: Point[]; byAssignee: Point[]; daily: { date: string; created: number; closed: number }[] }) {
  const statusData = byStatus.filter((item) => item.value > 0);
  return <div className="mt-6 grid gap-6 lg:grid-cols-2"><ChartBox title="Bugs by status"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={statusData} dataKey="value" nameKey="name" innerRadius={58} outerRadius={92} paddingAngle={2}>{statusData.map((item, index) => <Cell key={item.name} fill={colors[index % colors.length]} />)}</Pie><Tooltip contentStyle={tooltipStyle} /><Legend wrapperStyle={{ fontSize: 11 }} /></PieChart></ResponsiveContainer></ChartBox><ChartBox title="Bugs by priority"><ResponsiveContainer width="100%" height="100%"><BarChart data={byPriority}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" tick={{ fontSize: 11 }} /><YAxis allowDecimals={false} tick={{ fontSize: 11 }} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="value" name="Bugs" fill="#2563eb" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></ChartBox><ChartBox title="Bugs by developer"><ResponsiveContainer width="100%" height="100%"><BarChart data={byAssignee} layout="vertical" margin={{ left: 20 }}><CartesianGrid strokeDasharray="3 3" horizontal={false} /><XAxis type="number" allowDecimals={false} tick={{ fontSize: 11 }} /><YAxis type="category" dataKey="name" width={100} tick={{ fontSize: 11 }} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="value" name="Bugs" fill="#7c3aed" radius={[0, 5, 5, 0]} /></BarChart></ResponsiveContainer></ChartBox><ChartBox title="Created and closed — last 30 days"><ResponsiveContainer width="100%" height="100%"><LineChart data={daily}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="date" interval={4} tick={{ fontSize: 11 }} /><YAxis allowDecimals={false} tick={{ fontSize: 11 }} /><Tooltip contentStyle={tooltipStyle} /><Legend /><Line type="monotone" dataKey="created" stroke="#2563eb" strokeWidth={2} dot={false} /><Line type="monotone" dataKey="closed" stroke="#059669" strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer></ChartBox><ChartBox title="Bugs by severity"><ResponsiveContainer width="100%" height="100%"><BarChart data={bySeverity}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" tick={{ fontSize: 11 }} /><YAxis allowDecimals={false} tick={{ fontSize: 11 }} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="value" name="Bugs" fill="#dc2626" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></ChartBox></div>;
}
