"use client";
import Link from "next/link";
import { useState } from "react";
import { DndContext, PointerSensor, useDraggable, useDroppable, useSensor, useSensors, type DragEndEvent } from "@dnd-kit/core";
import type { BugStatus } from "@/generated/prisma/enums";
type Card = { id: string; bugCode: string; title: string; status: BugStatus; priority: string; dueDate: Date | null; assignee: { id: string; fullName: string } | null };
const columns: BugStatus[] = ["NEW", "ASSIGNED", "IN_PROGRESS", "READY_FOR_TEST", "REOPENED", "CLOSED"];
function BugCard({ bug }: { bug: Card }) { const { attributes, isDragging, listeners, setNodeRef, transform } = useDraggable({ id: bug.id, data: { status: bug.status } }); const style = { transform: transform ? `translate3d(${transform.x}px,${transform.y}px,0)` : undefined, opacity: isDragging ? .55 : 1 }; return <article ref={setNodeRef} {...listeners} {...attributes} style={style} className="cursor-grab rounded-lg border bg-white p-3 shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500"><Link href={`/bugs/${bug.id}`} className="font-mono text-xs font-semibold text-blue-600">{bug.bugCode}</Link><p className="mt-2 text-sm font-medium leading-5">{bug.title}</p><div className="mt-3 flex items-center justify-between gap-2 text-[11px] text-slate-500"><span className="rounded bg-slate-100 px-1.5 py-1">{bug.priority}</span><span className="truncate">{bug.assignee?.fullName ?? "Unassigned"}</span></div>{bug.dueDate ? <p className="mt-2 text-[11px] text-slate-400">Due {new Date(bug.dueDate).toLocaleDateString()}</p> : null}</article>; }
function Column({ status, bugs }: { status: BugStatus; bugs: Card[] }) { const { isOver, setNodeRef } = useDroppable({ id: status }); return <section ref={setNodeRef} className={`w-72 shrink-0 rounded-xl border p-3 ${isOver ? "border-blue-400 bg-blue-50" : "bg-slate-100/70"}`}><div className="mb-3 flex items-center justify-between"><h2 className="text-xs font-semibold tracking-wide">{status.replaceAll("_", " ")}</h2><span className="rounded-full bg-white px-2 py-0.5 text-xs text-slate-500">{bugs.length}</span></div><div className="space-y-3">{bugs.map((bug) => <BugCard key={bug.id} bug={bug} />)}{!bugs.length ? <div className="rounded-lg border border-dashed p-5 text-center text-xs text-slate-400">Drop here</div> : null}</div></section>; }
export function KanbanBoard({ initialBugs }: { initialBugs: Card[] }) { const [bugs, setBugs] = useState(initialBugs); const [toast, setToast] = useState(""); const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } })); async function onDragEnd(event: DragEndEvent) { const target = event.over?.id as BugStatus | undefined; const bug = bugs.find((item) => item.id === event.active.id); if (!bug || !target || target === bug.status) return; const before = bugs; setBugs((items) => items.map((item) => item.id === bug.id ? { ...item, status: target } : item)); const response = await fetch(`/api/bugs/${bug.id}/status`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: target }) }); const body = await response.json(); if (!response.ok) { setBugs(before); setToast(body.message || "Invalid transition; move was reverted."); } else setToast(`${bug.bugCode} moved to ${target.replaceAll("_", " ")}`); setTimeout(() => setToast(""), 3500); } return <><DndContext sensors={sensors} onDragEnd={onDragEnd}><div className="mt-6 flex gap-4 overflow-x-auto pb-5" aria-label="Bug Kanban board">{columns.map((status) => <Column key={status} status={status} bugs={bugs.filter((bug) => bug.status === status)} />)}</div></DndContext>{toast ? <div role="status" className="fixed bottom-5 right-5 z-50 max-w-sm rounded-lg bg-slate-950 px-4 py-3 text-sm text-white shadow-xl">{toast}</div> : null}</>; }
