import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { requirePageUser } from "@/lib/auth";
import { getProject } from "@/features/projects/service";
import { listProjectBoard } from "@/features/boards/service";
import { KanbanBoard } from "@/components/boards/kanban-board";
import type { BugPriority } from "@/generated/prisma/client";
const scalar = (value: string | string[] | undefined) => typeof value === "string" && value ? value : undefined;
export default async function ProjectBoardPage({ params, searchParams }: { params: Promise<{ projectId: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) { const actor = await requirePageUser(); const { projectId } = await params; const raw = await searchParams; const project = await getProject(projectId, actor); const assigneeId = scalar(raw.assigneeId); const priority = scalar(raw.priority) as BugPriority | undefined; const bugs = await listProjectBoard(projectId, actor, { assigneeId, priority }); const people = project.members.filter((member) => member.role === "DEVELOPER").map((member) => member.user); return <><Link href={`/projects/${projectId}`} className="inline-flex items-center gap-1 text-sm text-slate-500"><ArrowLeft className="size-4" />Dự án</Link><div className="mt-5"><p className="font-mono text-sm font-semibold text-blue-600">{project.code}</p><h1 className="mt-1 text-3xl font-semibold">Bảng Kanban</h1><p className="mt-2 text-slate-600">Kéo lỗi qua các bước chuyển trạng thái hợp lệ.</p></div><form className="mt-6 flex flex-wrap gap-3 rounded-xl border bg-white p-3"><select name="assigneeId" defaultValue={assigneeId ?? ""} aria-label="Lọc theo người phụ trách" className="h-10 rounded-lg border bg-white px-3 text-sm"><option value="">Tất cả người phụ trách</option>{people.map((person) => <option key={person.id} value={person.id}>{person.fullName}</option>)}</select><select name="priority" defaultValue={priority ?? ""} aria-label="Lọc theo độ ưu tiên" className="h-10 rounded-lg border bg-white px-3 text-sm"><option value="">Tất cả độ ưu tiên</option>{["LOW","MEDIUM","HIGH","URGENT"].map((value) => <option key={value}>{value}</option>)}</select><button className="h-10 rounded-lg bg-slate-900 px-4 text-sm text-white">Áp dụng</button></form><KanbanBoard initialBugs={bugs} /></>; }
