import Link from "next/link";
import { Bug, Plus, Search } from "lucide-react";
import type { BugQuery } from "@/lib/validators/bug";
import type { BugActor } from "@/features/bugs/service";
import { listBugs, listBugPeople, listBugProjects } from "@/features/bugs/service";
import { PriorityLabel, SeverityLabel, StatusBadge } from "@/components/bugs/bug-badges";

export async function BugList({ actor, query, raw, mine = false }: { actor: BugActor; query: BugQuery; raw: Record<string, string | string[] | undefined>; mine?: boolean }) {
  // Keep list-page reads sequential to stay within small Neon pool limits during dev cold starts.
  const result = await listBugs(actor, { ...query, mine });
  const projects = await listBugProjects(actor);
  const people = await listBugPeople(actor);
  return <><form className="mt-8 rounded-xl border bg-white p-3"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="relative sm:col-span-2"><Search className="absolute left-3 top-3 size-4 text-slate-400" /><input name="search" defaultValue={query.search} placeholder="Tìm theo mã hoặc tiêu đề" className="h-10 w-full rounded-lg border pl-9 pr-3 text-sm" /></div><select name="projectId" defaultValue={query.projectId ?? ""} className="h-10 rounded-lg border bg-white px-2 text-sm"><option value="">Tất cả dự án</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.code}</option>)}</select><select name="status" defaultValue={query.status ?? ""} className="h-10 rounded-lg border bg-white px-2 text-sm"><option value="">Tất cả trạng thái</option>{["NEW","ASSIGNED","IN_PROGRESS","RESOLVED","READY_FOR_TEST","REOPENED","CLOSED","REJECTED","DUPLICATE"].map((value) => <option key={value}>{value}</option>)}</select><select name="priority" defaultValue={query.priority ?? ""} className="h-10 rounded-lg border bg-white px-2 text-sm"><option value="">Tất cả độ ưu tiên</option>{["LOW","MEDIUM","HIGH","URGENT"].map((value) => <option key={value}>{value}</option>)}</select><select name="severity" defaultValue={query.severity ?? ""} className="h-10 rounded-lg border bg-white px-2 text-sm"><option value="">Tất cả mức độ</option>{["MINOR","MAJOR","CRITICAL","BLOCKER"].map((value) => <option key={value}>{value}</option>)}</select><select name="assigneeId" defaultValue={query.assigneeId ?? ""} className="h-10 rounded-lg border bg-white px-2 text-sm"><option value="">Tất cả người phụ trách</option>{people.map((person) => <option key={person.id} value={person.id}>{person.fullName}</option>)}</select><select name="reporterId" defaultValue={query.reporterId ?? ""} className="h-10 rounded-lg border bg-white px-2 text-sm"><option value="">Tất cả người báo cáo</option>{people.map((person) => <option key={person.id} value={person.id}>{person.fullName}</option>)}</select><select name="sortBy" defaultValue={query.sortBy} className="h-10 rounded-lg border bg-white px-2 text-sm"><option value="createdAt">Mới tạo nhất</option><option value="updatedAt">Mới cập nhật</option><option value="dueDate">Hạn xử lý</option><option value="priority">Độ ưu tiên</option><option value="severity">Mức độ nghiêm trọng</option></select><select name="sortOrder" defaultValue={query.sortOrder} className="h-10 rounded-lg border bg-white px-2 text-sm"><option value="desc">Giảm dần</option><option value="asc">Tăng dần</option></select><label className="flex h-10 items-center gap-2 px-2 text-sm text-slate-600"><input type="checkbox" name="overdue" value="true" defaultChecked={query.overdue} />Chỉ lỗi quá hạn</label><button className="h-10 rounded-lg bg-slate-950 px-4 text-sm font-medium text-white">Áp dụng bộ lọc</button></div></form>
    {result.items.length ? <div className="mt-6 overflow-hidden rounded-xl border bg-white"><div className="divide-y">{result.items.map((bug) => { const overdue = bug.dueDate && bug.dueDate < new Date() && !["CLOSED","REJECTED","DUPLICATE"].includes(bug.status); return <Link href={`/bugs/${bug.id}`} key={bug.id} className="grid gap-3 p-4 transition hover:bg-slate-50 md:grid-cols-[100px_minmax(240px,1fr)_130px_90px_90px_150px] md:items-center"><span className="font-mono text-xs font-semibold text-blue-600">{bug.bugCode}</span><div className="min-w-0"><p className="truncate text-sm font-medium">{bug.title}</p><p className="mt-1 text-xs text-slate-500">{bug.project.name}</p></div><StatusBadge value={bug.status} /><PriorityLabel value={bug.priority} /><SeverityLabel value={bug.severity} /><div className="text-xs text-slate-500"><p>{bug.assignee?.fullName ?? "Chưa phân công"}</p>{bug.dueDate ? <p className={overdue ? "mt-1 font-medium text-red-600" : "mt-1"}>{overdue ? "Quá hạn · " : "Hạn · "}{bug.dueDate.toLocaleDateString("vi-VN")}</p> : null}</div></Link>; })}</div></div> : <div className="mt-6 grid min-h-64 place-items-center rounded-xl border border-dashed bg-white text-center"><div><Bug className="mx-auto size-8 text-slate-300" /><h2 className="mt-3 font-medium">Không tìm thấy lỗi</h2><p className="mt-1 text-sm text-slate-500">Hãy điều chỉnh bộ lọc hoặc báo một lỗi mới.</p></div></div>}
    <div className="mt-6 flex items-center justify-between text-sm text-slate-500"><span>{result.pagination.total} lỗi</span><div className="flex gap-2">{query.page > 1 ? <Link className="rounded-lg border bg-white px-3 py-2" href={{ query: { ...raw, page: query.page - 1 } }}>Trước</Link> : null}{query.page < result.pagination.totalPages ? <Link className="rounded-lg border bg-white px-3 py-2" href={{ query: { ...raw, page: query.page + 1 } }}>Sau</Link> : null}</div></div></>;
}

export function NewBugLink() { return <Link href="/bugs/new" className="flex h-10 items-center gap-2 rounded-lg bg-blue-600 px-4 text-sm font-medium text-white"><Plus className="size-4" />Báo lỗi</Link>; }
