"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Link2, Search, Trash2, X } from "lucide-react";
import { PriorityLabel, StatusBadge } from "@/components/bugs/bug-badges";
import type { BugLinkType, BugPriority, BugStatus } from "@/generated/prisma/client";
type Bug={id:string;bugCode:string;title:string;status:BugStatus;priority:BugPriority;project:{id:string;code:string;name:string}};
type Item={id:string;sourceBugId:string;targetBugId:string;type:BugLinkType;direction:"OUTGOING"|"INCOMING";relatedBug:Bug;canDelete:boolean};
type Envelope<T>={success:boolean;message:string;data?:T};
const labels:Record<BugLinkType,string>={DUPLICATE:"Trùng lặp",BLOCKED_BY:"Bị chặn bởi",RELATES_TO:"Liên quan"};
function relation(x:Item){if(x.type==="RELATES_TO")return"Liên quan";if(x.type==="DUPLICATE")return x.direction==="OUTGOING"?"Trùng với":"Có bug trùng";return x.direction==="OUTGOING"?"Đang chặn bug này":"Bug này đang chặn";}
export function BugLinks({bugId,initialLinks,canCreate}:{bugId:string;initialLinks:Item[];canCreate:boolean}){
 const[items,setItems]=useState(initialLinks),[open,setOpen]=useState(false),[query,setQuery]=useState(""),[results,setResults]=useState<Bug[]>([]),[target,setTarget]=useState<Bug|null>(null),[type,setType]=useState<BugLinkType>("RELATES_TO"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function reload(){const r=await fetch(`/api/bugs/${bugId}/links`),b=await r.json() as Envelope<Item[]>;if(b.data)setItems(b.data);}
 useEffect(()=>{if(!open||target||query.trim().length<2)return;const timer=window.setTimeout(async()=>{try{const r=await fetch(`/api/bugs?search=${encodeURIComponent(query)}&pageSize=10`),b=await r.json() as Envelope<{items:Bug[]}>;if(!r.ok)throw new Error();setResults((b.data?.items??[]).filter(x=>x.id!==bugId));}catch{setError("Không thể tìm kiếm bug lúc này.");}},300);return()=>window.clearTimeout(timer);},[bugId,open,query,target]);
 async function create(){if(!target)return;setBusy(true);setError("");try{const r=await fetch(`/api/bugs/${bugId}/links`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({targetBugId:target.id,type})}),b=await r.json() as Envelope<unknown>;if(!r.ok)throw new Error(b.message);await reload();setOpen(false);setTarget(null);setQuery("");}catch(e){setError(e instanceof Error?e.message:"Không thể liên kết bug.");}finally{setBusy(false);}}
 async function remove(id:string){setBusy(true);setError("");try{const r=await fetch(`/api/bugs/${bugId}/links/${id}`,{method:"DELETE"}),b=await r.json() as Envelope<unknown>;if(!r.ok)throw new Error(b.message);setItems(v=>v.filter(x=>x.id!==id));}catch(e){setError(e instanceof Error?e.message:"Không thể xóa liên kết.");}finally{setBusy(false);}}
 return <section className="mt-10 rounded-xl border bg-white p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">Bug liên kết</h2><p className="mt-1 text-sm text-slate-500">Các quan hệ được hiển thị theo cả hai chiều.</p></div>{canCreate?<button onClick={()=>{setOpen(true);setError("");}} className="inline-flex h-9 items-center gap-2 rounded-lg bg-blue-600 px-3 text-sm font-medium text-white"><Link2 className="size-4"/>Liên kết bug</button>:null}</div>
 {error&&!open?<p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}{items.length===0?<p className="mt-5 rounded-lg bg-slate-50 p-4 text-sm text-slate-500">Chưa có bug liên kết.</p>:<div className="mt-5 divide-y">{items.map(x=><div key={x.id} className="flex items-center gap-3 py-4"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-medium">{relation(x)}</span><span className="text-xs text-slate-500">{x.relatedBug.project.name}</span></div><Link href={`/bugs/${x.relatedBug.id}`} className="mt-2 block truncate font-medium text-blue-700 hover:underline">{x.relatedBug.bugCode} · {x.relatedBug.title}</Link><div className="mt-2 flex items-center gap-3"><StatusBadge value={x.relatedBug.status}/><PriorityLabel value={x.relatedBug.priority}/></div></div>{x.canDelete?<button disabled={busy} onClick={()=>remove(x.id)} aria-label="Xóa liên kết" className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600 disabled:opacity-50"><Trash2 className="size-4"/></button>:null}</div>)}</div>}
 {open?<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><h3 className="text-lg font-semibold">Liên kết bug</h3><button onClick={()=>setOpen(false)} aria-label="Đóng" className="rounded-lg p-2 hover:bg-slate-100"><X className="size-5"/></button></div><label className="mt-5 block text-sm font-medium">Loại quan hệ<select value={type} onChange={e=>setType(e.target.value as BugLinkType)} className="mt-2 h-11 w-full rounded-lg border bg-white px-3">{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="mt-4 block text-sm font-medium">Bug đích<div className="relative mt-2"><Search className="absolute left-3 top-3 size-5 text-slate-400"/><input value={target?`${target.bugCode} · ${target.title}`:query} onChange={e=>{setTarget(null);setQuery(e.target.value);setError("");}} placeholder="Tìm theo mã hoặc tiêu đề..." className="h-11 w-full rounded-lg border pl-10 pr-3"/></div></label>{!target&&query.trim().length>=2?<div className="mt-2 max-h-56 overflow-auto rounded-lg border">{results.length?results.map(b=><button key={b.id} onClick={()=>setTarget(b)} className="block w-full border-b p-3 text-left last:border-0 hover:bg-slate-50"><span className="font-medium">{b.bugCode} · {b.title}</span><span className="mt-1 block text-xs text-slate-500">{b.project.name} · {b.status} · {b.priority}</span></button>):<p className="p-3 text-sm text-slate-500">Không tìm thấy bug phù hợp.</p>}</div>:null}{error?<p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}<div className="mt-6 flex justify-end gap-2"><button onClick={()=>setOpen(false)} className="h-10 rounded-lg border px-4 text-sm">Hủy</button><button disabled={!target||busy} onClick={create} className="h-10 rounded-lg bg-blue-600 px-4 text-sm font-medium text-white disabled:opacity-50">{busy?"Đang lưu...":"Lưu liên kết"}</button></div></div></div>:null}</section>;
}
