"use client";

import Image from "next/image";
import { useActionState } from "react";
import { beginTwoFactorSetupAction, confirmTwoFactorSetupAction, disableTwoFactorAction, regenerateRecoveryCodesAction } from "@/features/auth/two-factor-actions";

function Message({ state }: { state: { success: boolean; message: string } | undefined }) { return state ? <p role="status" className={`rounded-lg p-3 text-sm ${state.success ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{state.message}</p> : null; }
function RecoveryCodes({ codes }: { codes?: string[] }) { return codes?.length ? <section className="rounded-xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-semibold text-amber-950">Lưu recovery code ngay bây giờ</h2><p className="mt-1 text-sm text-amber-800">Các code này chỉ hiển thị một lần. Không chia sẻ và không lưu vào nơi công khai.</p><ul className="mt-4 grid gap-2 sm:grid-cols-2">{codes.map((code) => <li key={code} className="rounded-lg border bg-white px-3 py-2 text-center font-mono text-sm">{code}</li>)}</ul></section> : null; }

export function TwoFactorSetupForm() {
  const [setup, setupAction, setupPending] = useActionState(beginTwoFactorSetupAction, undefined);
  const [confirm, confirmAction, confirmPending] = useActionState(confirmTwoFactorSetupAction, undefined);
  return <div className="space-y-6">{!setup?.qrCodeDataUrl ? <form action={setupAction} className="space-y-4 rounded-xl border bg-white p-6"><h2 className="font-semibold">Bắt đầu thiết lập</h2><p className="text-sm text-slate-500">Nhập lại mật khẩu trước khi tạo QR code.</p><label className="block text-sm font-medium">Mật khẩu hiện tại<input name="password" type="password" required autoComplete="current-password" className="mt-1.5 h-10 w-full rounded-lg border px-3" /></label><Message state={setup} /><button disabled={setupPending} className="h-10 rounded-lg bg-blue-600 px-4 text-sm font-medium text-white disabled:opacity-60">{setupPending ? "Đang tạo…" : "Tạo QR code"}</button></form> : <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl border bg-white p-6 text-center"><h2 className="font-semibold">Quét QR code</h2><p className="mt-1 text-sm text-slate-500">Dùng Google Authenticator, Microsoft Authenticator, Authy, 1Password hoặc ứng dụng TOTP tương thích.</p><Image src={setup.qrCodeDataUrl} alt="QR code thiết lập two-factor authentication" width={280} height={280} unoptimized className="mx-auto mt-5" /></section><form action={confirmAction} className="space-y-4 rounded-xl border bg-white p-6"><h2 className="font-semibold">Xác nhận mã đầu tiên</h2><p className="text-sm text-slate-500">Tài khoản chỉ được bật 2FA sau khi mã này hợp lệ.</p><label className="block text-sm font-medium">Mã xác thực<input name="code" autoFocus required inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} className="mt-1.5 h-11 w-full rounded-lg border px-3 text-center font-mono text-lg tracking-widest" /></label><Message state={confirm} /><button disabled={confirmPending} className="h-10 rounded-lg bg-blue-600 px-4 text-sm font-medium text-white disabled:opacity-60">{confirmPending ? "Đang xác nhận…" : "Bật 2FA"}</button></form></div>}<RecoveryCodes codes={confirm?.recoveryCodes} /></div>;
}

export function TwoFactorManagement() {
  const [disable, disableAction, disablePending] = useActionState(disableTwoFactorAction, undefined);
  const [regenerate, regenerateAction, regeneratePending] = useActionState(regenerateRecoveryCodesAction, undefined);
  return <div className="grid gap-6 lg:grid-cols-2"><form action={regenerateAction} className="space-y-4 rounded-xl border bg-white p-6"><h2 className="font-semibold">Tạo lại recovery code</h2><p className="text-sm text-slate-500">Bộ code cũ sẽ bị vô hiệu hóa. Nhập lại mật khẩu để tiếp tục.</p><input name="password" type="password" required aria-label="Mật khẩu hiện tại" autoComplete="current-password" className="h-10 w-full rounded-lg border px-3" /><Message state={regenerate} /><button disabled={regeneratePending} className="h-10 rounded-lg border px-4 text-sm font-medium disabled:opacity-60">{regeneratePending ? "Đang tạo…" : "Tạo bộ code mới"}</button><RecoveryCodes codes={regenerate?.recoveryCodes} /></form><form action={disableAction} className="space-y-4 rounded-xl border border-red-200 bg-red-50/40 p-6"><h2 className="font-semibold text-red-900">Tắt two-factor authentication</h2><p className="text-sm text-red-700">Thao tác này xóa secret, recovery code và mọi challenge còn hiệu lực.</p><input name="password" type="password" required aria-label="Mật khẩu hiện tại" placeholder="Mật khẩu hiện tại" autoComplete="current-password" className="h-10 w-full rounded-lg border bg-white px-3" /><select name="method" aria-label="Phương thức xác minh" className="h-10 w-full rounded-lg border bg-white px-3 text-sm"><option value="totp">Mã Authenticator</option><option value="recovery">Recovery code</option></select><input name="verification" required aria-label="Mã xác thực" placeholder="Mã xác thực hoặc recovery code" className="h-10 w-full rounded-lg border bg-white px-3" /><Message state={disable} /><button disabled={disablePending} className="h-10 rounded-lg bg-red-700 px-4 text-sm font-medium text-white disabled:opacity-60">{disablePending ? "Đang tắt…" : "Tắt 2FA"}</button></form></div>;
}
